@baseUrl=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWlicDZtYWUwMDAxYm80YzhiZ21nbnZlIiwibmFtZSI6ImdoYWxhc3MiLCJlbWFpbCI6ImdoYWxhc3NAZ21haWwuY29tIiwicm9sZXMiOlt7ImlkIjoiY21pYnA1a2R6MDAwMGJvOHc4ZGdkNDk2diIsIm5hbWUiOiJhZG1pbiIsImNyZWF0ZWRBdCI6IjIwMjUtMTEtMjNUMTI6NDg6NDUuNTM0WiIsInVwZGF0ZWRBdCI6IjIwMjUtMTEtMjNUMTI6MzE6MTAuMTk5WiJ9LHsiaWQiOiJjbWlicDZtYTkwMDAwYm80YzU4djd2Y216IiwibmFtZSI6IlN1cGVyIEFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNS0xMS0yM1QxMjo0ODo0NS41MzRaIiwidXBkYXRlZEF0IjoiMjAyNS0xMS0yM1QxMjozMTo1OS4zMTRaIn0seyJpZCI6ImNtaWJ0ZHVhcDAwMDBibzlzOGxoenY5bjUiLCJuYW1lIjoiVXNlciIsImNyZWF0ZWRBdCI6IjIwMjUtMTEtMjNUMTQ6Mjk6MzQuNzU0WiIsInVwZGF0ZWRBdCI6IjIwMjUtMTEtMjNUMTQ6Mjk6MzQuNzU0WiJ9XSwiaWF0IjoxNzY0NTIwMjUyLCJleHAiOjE3NjQ1NDU0NTJ9.Z7jWXjiBNm09H3kILqyELkW2Z9VsOfsrtPGUDgHBqY0

### GET ROLES
GET {{baseUrl}}/sites
Cookie: jwt={{token}}