@baseUrl=http://localhost:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWlicDZtYWUwMDAxYm80YzhiZ21nbnZlIiwibmFtZSI6ImdoYWxhc3MiLCJlbWFpbCI6ImdoYWxhc3NAZ21haWwuY29tIiwicm9sZXMiOlt7ImlkIjoiY21pYnA2bWE5MDAwMGJvNGM1OHY3dmNteiIsIm5hbWUiOiJTdXBlciBBZG1pbiIsImNyZWF0ZWRkQXQiOiIyMDI1LTExLTIzVDEyOjMxOjU5LjMxNFoiLCJ1cGRhdGVkQXQiOiIyMDI1LTExLTIzVDEyOjMxOjU5LjMxNFoifV0sImlhdCI6MTc2MzkwMTEyNCwiZXhwIjoxNzYzOTI2MzI0fQ.tQIzG_2VtcV29I0qkzf3OgFwdqTimpXf4cEAXn9r-9A

### GET ROLES
GET {{baseUrl}}/permissions
Cookie: jwt={{token}}

### CREATE ROLE
POST {{baseUrl}}/permissions
Cookie: jwt={{token}}
Content-Type: application/json

{
    "name": "test",
}

### DELETE ROLE
DELETE {{baseUrl}}/permissions/cmibpyagm0000bockxex5tujr
Cookie: jwt={{token}}